name: uber_mobile_app_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  hive_flutter: ^1.1.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.4
  multi_select_flutter: ^4.1.3
  uuid: ^4.5.1
  dartz: ^0.10.1
  path_provider: ^2.1.5
  equatable: ^2.0.7
  image_picker: ^1.1.2
  awesome_dio_interceptor: ^1.3.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.1
  permission_handler: ^11.3.1
  json_serializable: ^6.9.0
  get_it: ^8.0.3
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  google_maps_flutter: ^2.10.0
  freezed_annotation: ^2.4.4
  build_runner: ^2.4.14
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  hive: ^2.2.3
  smooth_page_indicator: ^1.2.0+3
  flutter_map: ^8.1.0
  latlong2: ^0.9.1
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 300

    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
          weight: 300
