name: uber_mobile_app_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ✅ Networking & HTTP
  dio: ^5.7.0
  awesome_dio_interceptor: ^1.3.0
  pretty_dio_logger: ^1.4.0

  # ✅ Local Storage
  hive: ^2.2.3  # ✅ Added
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.4
  path_provider: ^2.1.5

  # ✅ State Management & Utilities
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.3

  # ✅ Serialization
  json_annotation: ^4.8.1  # ⚠️ Downgraded to match required version

  # ✅ Permissions & Connectivity
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.1

  # ✅ UI Widgets
  multi_select_flutter: ^4.1.3
  uuid: ^4.5.1
  image_picker: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # ✅ Code Generation
  build_runner: ^2.4.6  # ⚠️ Downgraded to match required version
  hive_generator: ^2.0.0  # ⚠️ Downgraded to match required version
  json_serializable: ^6.7.1  # ⚠️ Downgraded to match required version

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 300

    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
          weight: 300
